// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: conference.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type StartConferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID           string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Type             string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title            string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description      string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Interest         string `protobuf:"bytes,5,opt,name=interest,proto3" json:"interest,omitempty"`
	Recording        bool   `protobuf:"varint,6,opt,name=recording,proto3" json:"recording,omitempty"`
	Chat             bool   `protobuf:"varint,7,opt,name=chat,proto3" json:"chat,omitempty"`
	Broadcast        bool   `protobuf:"varint,8,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
	Participantlimit int32  `protobuf:"varint,9,opt,name=participantlimit,proto3" json:"participantlimit,omitempty"`
}

func (x *StartConferenceRequest) Reset() {
	*x = StartConferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartConferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartConferenceRequest) ProtoMessage() {}

func (x *StartConferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartConferenceRequest.ProtoReflect.Descriptor instead.
func (*StartConferenceRequest) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{2}
}

func (x *StartConferenceRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *StartConferenceRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StartConferenceRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StartConferenceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StartConferenceRequest) GetInterest() string {
	if x != nil {
		return x.Interest
	}
	return ""
}

func (x *StartConferenceRequest) GetRecording() bool {
	if x != nil {
		return x.Recording
	}
	return false
}

func (x *StartConferenceRequest) GetChat() bool {
	if x != nil {
		return x.Chat
	}
	return false
}

func (x *StartConferenceRequest) GetBroadcast() bool {
	if x != nil {
		return x.Broadcast
	}
	return false
}

func (x *StartConferenceRequest) GetParticipantlimit() int32 {
	if x != nil {
		return x.Participantlimit
	}
	return 0
}

type StartConferenceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Link         string `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Offer        string `protobuf:"bytes,2,opt,name=offer,proto3" json:"offer,omitempty"`
	ConferenceID int32  `protobuf:"varint,3,opt,name=conferenceID,proto3" json:"conferenceID,omitempty"`
}

func (x *StartConferenceResponse) Reset() {
	*x = StartConferenceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartConferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartConferenceResponse) ProtoMessage() {}

func (x *StartConferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartConferenceResponse.ProtoReflect.Descriptor instead.
func (*StartConferenceResponse) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{3}
}

func (x *StartConferenceResponse) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *StartConferenceResponse) GetOffer() string {
	if x != nil {
		return x.Offer
	}
	return ""
}

func (x *StartConferenceResponse) GetConferenceID() int32 {
	if x != nil {
		return x.ConferenceID
	}
	return 0
}

type JoinConferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ConferenceID int32  `protobuf:"varint,2,opt,name=conferenceID,proto3" json:"conferenceID,omitempty"`
}

func (x *JoinConferenceRequest) Reset() {
	*x = JoinConferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinConferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinConferenceRequest) ProtoMessage() {}

func (x *JoinConferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinConferenceRequest.ProtoReflect.Descriptor instead.
func (*JoinConferenceRequest) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{4}
}

func (x *JoinConferenceRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *JoinConferenceRequest) GetConferenceID() int32 {
	if x != nil {
		return x.ConferenceID
	}
	return 0
}

type JoinConferenceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *JoinConferenceResponse) Reset() {
	*x = JoinConferenceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinConferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinConferenceResponse) ProtoMessage() {}

func (x *JoinConferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinConferenceResponse.ProtoReflect.Descriptor instead.
func (*JoinConferenceResponse) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{5}
}

func (x *JoinConferenceResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type AcceptJoiningRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ConferenceID string `protobuf:"bytes,2,opt,name=conferenceID,proto3" json:"conferenceID,omitempty"`
}

func (x *AcceptJoiningRequest) Reset() {
	*x = AcceptJoiningRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptJoiningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptJoiningRequest) ProtoMessage() {}

func (x *AcceptJoiningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptJoiningRequest.ProtoReflect.Descriptor instead.
func (*AcceptJoiningRequest) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{6}
}

func (x *AcceptJoiningRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *AcceptJoiningRequest) GetConferenceID() string {
	if x != nil {
		return x.ConferenceID
	}
	return ""
}

type AcceptJoiningResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AcceptJoiningResponse) Reset() {
	*x = AcceptJoiningResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptJoiningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptJoiningResponse) ProtoMessage() {}

func (x *AcceptJoiningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptJoiningResponse.ProtoReflect.Descriptor instead.
func (*AcceptJoiningResponse) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{7}
}

func (x *AcceptJoiningResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

// Decline Joining
type DeclineJoiningRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ConferenceID string `protobuf:"bytes,2,opt,name=conferenceID,proto3" json:"conferenceID,omitempty"`
}

func (x *DeclineJoiningRequest) Reset() {
	*x = DeclineJoiningRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeclineJoiningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineJoiningRequest) ProtoMessage() {}

func (x *DeclineJoiningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineJoiningRequest.ProtoReflect.Descriptor instead.
func (*DeclineJoiningRequest) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{8}
}

func (x *DeclineJoiningRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DeclineJoiningRequest) GetConferenceID() string {
	if x != nil {
		return x.ConferenceID
	}
	return ""
}

type DeclineJoiningResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *DeclineJoiningResponse) Reset() {
	*x = DeclineJoiningResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeclineJoiningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeclineJoiningResponse) ProtoMessage() {}

func (x *DeclineJoiningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeclineJoiningResponse.ProtoReflect.Descriptor instead.
func (*DeclineJoiningResponse) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{9}
}

func (x *DeclineJoiningResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type RemoveParticipantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ConferenceID string `protobuf:"bytes,2,opt,name=conferenceID,proto3" json:"conferenceID,omitempty"`
	Block        bool   `protobuf:"varint,3,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *RemoveParticipantRequest) Reset() {
	*x = RemoveParticipantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParticipantRequest) ProtoMessage() {}

func (x *RemoveParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParticipantRequest.ProtoReflect.Descriptor instead.
func (*RemoveParticipantRequest) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveParticipantRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *RemoveParticipantRequest) GetConferenceID() string {
	if x != nil {
		return x.ConferenceID
	}
	return ""
}

func (x *RemoveParticipantRequest) GetBlock() bool {
	if x != nil {
		return x.Block
	}
	return false
}

type RemoveParticipantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *RemoveParticipantResponse) Reset() {
	*x = RemoveParticipantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParticipantResponse) ProtoMessage() {}

func (x *RemoveParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParticipantResponse.ProtoReflect.Descriptor instead.
func (*RemoveParticipantResponse) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveParticipantResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ToggleCameraRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ConferenceID string `protobuf:"bytes,2,opt,name=conferenceID,proto3" json:"conferenceID,omitempty"`
}

func (x *ToggleCameraRequest) Reset() {
	*x = ToggleCameraRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToggleCameraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleCameraRequest) ProtoMessage() {}

func (x *ToggleCameraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleCameraRequest.ProtoReflect.Descriptor instead.
func (*ToggleCameraRequest) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{12}
}

func (x *ToggleCameraRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ToggleCameraRequest) GetConferenceID() string {
	if x != nil {
		return x.ConferenceID
	}
	return ""
}

type ToggleCameraResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ToggleCameraResponse) Reset() {
	*x = ToggleCameraResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToggleCameraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleCameraResponse) ProtoMessage() {}

func (x *ToggleCameraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleCameraResponse.ProtoReflect.Descriptor instead.
func (*ToggleCameraResponse) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{13}
}

func (x *ToggleCameraResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ToggleMicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ConferenceID string `protobuf:"bytes,2,opt,name=conferenceID,proto3" json:"conferenceID,omitempty"`
}

func (x *ToggleMicRequest) Reset() {
	*x = ToggleMicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToggleMicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleMicRequest) ProtoMessage() {}

func (x *ToggleMicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleMicRequest.ProtoReflect.Descriptor instead.
func (*ToggleMicRequest) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{14}
}

func (x *ToggleMicRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ToggleMicRequest) GetConferenceID() string {
	if x != nil {
		return x.ConferenceID
	}
	return ""
}

type ToggleMicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ToggleMicResponse) Reset() {
	*x = ToggleMicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToggleMicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleMicResponse) ProtoMessage() {}

func (x *ToggleMicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleMicResponse.ProtoReflect.Descriptor instead.
func (*ToggleMicResponse) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{15}
}

func (x *ToggleMicResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ToggleParticipantCameraRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ConferenceID string `protobuf:"bytes,2,opt,name=conferenceID,proto3" json:"conferenceID,omitempty"`
}

func (x *ToggleParticipantCameraRequest) Reset() {
	*x = ToggleParticipantCameraRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToggleParticipantCameraRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleParticipantCameraRequest) ProtoMessage() {}

func (x *ToggleParticipantCameraRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleParticipantCameraRequest.ProtoReflect.Descriptor instead.
func (*ToggleParticipantCameraRequest) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{16}
}

func (x *ToggleParticipantCameraRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ToggleParticipantCameraRequest) GetConferenceID() string {
	if x != nil {
		return x.ConferenceID
	}
	return ""
}

type ToggleParticipantCameraResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ToggleParticipantCameraResponse) Reset() {
	*x = ToggleParticipantCameraResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToggleParticipantCameraResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleParticipantCameraResponse) ProtoMessage() {}

func (x *ToggleParticipantCameraResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleParticipantCameraResponse.ProtoReflect.Descriptor instead.
func (*ToggleParticipantCameraResponse) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{17}
}

func (x *ToggleParticipantCameraResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ToggleParticipantMicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ConferenceID string `protobuf:"bytes,2,opt,name=conferenceID,proto3" json:"conferenceID,omitempty"`
}

func (x *ToggleParticipantMicRequest) Reset() {
	*x = ToggleParticipantMicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToggleParticipantMicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleParticipantMicRequest) ProtoMessage() {}

func (x *ToggleParticipantMicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleParticipantMicRequest.ProtoReflect.Descriptor instead.
func (*ToggleParticipantMicRequest) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{18}
}

func (x *ToggleParticipantMicRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *ToggleParticipantMicRequest) GetConferenceID() string {
	if x != nil {
		return x.ConferenceID
	}
	return ""
}

type ToggleParticipantMicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ToggleParticipantMicResponse) Reset() {
	*x = ToggleParticipantMicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToggleParticipantMicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleParticipantMicResponse) ProtoMessage() {}

func (x *ToggleParticipantMicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleParticipantMicResponse.ProtoReflect.Descriptor instead.
func (*ToggleParticipantMicResponse) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{19}
}

func (x *ToggleParticipantMicResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type LeaveConferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ConferenceID string `protobuf:"bytes,2,opt,name=conferenceID,proto3" json:"conferenceID,omitempty"`
}

func (x *LeaveConferenceRequest) Reset() {
	*x = LeaveConferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveConferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveConferenceRequest) ProtoMessage() {}

func (x *LeaveConferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveConferenceRequest.ProtoReflect.Descriptor instead.
func (*LeaveConferenceRequest) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{20}
}

func (x *LeaveConferenceRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *LeaveConferenceRequest) GetConferenceID() string {
	if x != nil {
		return x.ConferenceID
	}
	return ""
}

type LeaveConferenceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *LeaveConferenceResponse) Reset() {
	*x = LeaveConferenceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaveConferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveConferenceResponse) ProtoMessage() {}

func (x *LeaveConferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveConferenceResponse.ProtoReflect.Descriptor instead.
func (*LeaveConferenceResponse) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{21}
}

func (x *LeaveConferenceResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type EndConferenceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID       string `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ConferenceID string `protobuf:"bytes,2,opt,name=conferenceID,proto3" json:"conferenceID,omitempty"`
}

func (x *EndConferenceRequest) Reset() {
	*x = EndConferenceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndConferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndConferenceRequest) ProtoMessage() {}

func (x *EndConferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndConferenceRequest.ProtoReflect.Descriptor instead.
func (*EndConferenceRequest) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{22}
}

func (x *EndConferenceRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *EndConferenceRequest) GetConferenceID() string {
	if x != nil {
		return x.ConferenceID
	}
	return ""
}

type EndConferenceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *EndConferenceResponse) Reset() {
	*x = EndConferenceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_conference_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndConferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndConferenceResponse) ProtoMessage() {}

func (x *EndConferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_conference_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndConferenceResponse.ProtoReflect.Descriptor instead.
func (*EndConferenceResponse) Descriptor() ([]byte, []int) {
	return file_conference_proto_rawDescGZIP(), []int{23}
}

func (x *EndConferenceResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_conference_proto protoreflect.FileDescriptor

var file_conference_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x1d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x22, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x94, 0x02, 0x0a, 0x16, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x65, 0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69, 0x6e,
	0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x68, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x63, 0x68, 0x61, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63,
	0x61, 0x73, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x62, 0x72, 0x6f, 0x61, 0x64,
	0x63, 0x61, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70,
	0x61, 0x6e, 0x74, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10,
	0x70, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x22, 0x67, 0x0a, 0x17, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c,
	0x69, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12,
	0x14, 0x0a, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6f, 0x66, 0x66, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x6f, 0x6e,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x22, 0x53, 0x0a, 0x15, 0x4a, 0x6f, 0x69,
	0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f,
	0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x22, 0x30,
	0x0a, 0x16, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x52, 0x0a, 0x14, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x49, 0x44, 0x22, 0x2f, 0x0a, 0x15, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4a, 0x6f,
	0x69, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x53, 0x0a, 0x15, 0x44, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65,
	0x4a, 0x6f, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f,
	0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x22, 0x30, 0x0a, 0x16, 0x44, 0x65,
	0x63, 0x6c, 0x69, 0x6e, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x6c, 0x0a, 0x18,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x33, 0x0a, 0x19, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x51, 0x0a, 0x13, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22,
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x49, 0x44, 0x22, 0x2e, 0x0a, 0x14, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x43, 0x61, 0x6d, 0x65,
	0x72, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x4e, 0x0a, 0x10, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4d, 0x69, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22,
	0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x49, 0x44, 0x22, 0x2b, 0x0a, 0x11, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4d, 0x69, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x5c, 0x0a, 0x1e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69,
	0x70, 0x61, 0x6e, 0x74, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x22, 0x39, 0x0a,
	0x1f, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61,
	0x6e, 0x74, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x59, 0x0a, 0x1b, 0x54, 0x6f, 0x67, 0x67,
	0x6c, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x4d, 0x69, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x49, 0x44, 0x22, 0x36, 0x0a, 0x1c, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x4d, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x54, 0x0a, 0x16, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a,
	0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49,
	0x44, 0x22, 0x31, 0x0a, 0x17, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x52, 0x0a, 0x14, 0x45, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x44, 0x22, 0x2f, 0x0a, 0x15, 0x45, 0x6e, 0x64, 0x43,
	0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xc2, 0x06, 0x0a, 0x0a, 0x43, 0x6f,
	0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x0b, 0x48, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x0b, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x43, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x49, 0x0a, 0x0e, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x70, 0x62, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0d, 0x41,
	0x63, 0x63, 0x65, 0x70, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x2e, 0x70,
	0x62, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x65,
	0x70, 0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0e, 0x44, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x4a, 0x6f,
	0x69, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x63, 0x6c, 0x69,
	0x6e, 0x65, 0x4a, 0x6f, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x63, 0x6c, 0x69, 0x6e, 0x65, 0x4a, 0x6f, 0x69,
	0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52,
	0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70,
	0x61, 0x6e, 0x74, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x43, 0x0a, 0x0c, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x43, 0x61, 0x6d, 0x65,
	0x72, 0x61, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x43, 0x61,
	0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62,
	0x2e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x09, 0x54, 0x6f, 0x67, 0x67, 0x6c,
	0x65, 0x4d, 0x69, 0x63, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65,
	0x4d, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e,
	0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4d, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x17, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x12, 0x22,
	0x2e, 0x70, 0x62, 0x2e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x69, 0x70, 0x61, 0x6e, 0x74, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x23, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x50, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x43, 0x61, 0x6d, 0x65, 0x72, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x14, 0x54, 0x6f, 0x67,
	0x67, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x4d, 0x69,
	0x63, 0x12, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x50, 0x61, 0x72,
	0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x4d, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x50, 0x61,
	0x72, 0x74, 0x69, 0x63, 0x69, 0x70, 0x61, 0x6e, 0x74, 0x4d, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0d, 0x45, 0x6e, 0x64, 0x43, 0x6f, 0x6e,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x64,
	0x43, 0x6f, 0x6e, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x05,
	0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_conference_proto_rawDescOnce sync.Once
	file_conference_proto_rawDescData = file_conference_proto_rawDesc
)

func file_conference_proto_rawDescGZIP() []byte {
	file_conference_proto_rawDescOnce.Do(func() {
		file_conference_proto_rawDescData = protoimpl.X.CompressGZIP(file_conference_proto_rawDescData)
	})
	return file_conference_proto_rawDescData
}

var file_conference_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_conference_proto_goTypes = []interface{}{
	(*Request)(nil),                         // 0: pb.Request
	(*Response)(nil),                        // 1: pb.Response
	(*StartConferenceRequest)(nil),          // 2: pb.StartConferenceRequest
	(*StartConferenceResponse)(nil),         // 3: pb.StartConferenceResponse
	(*JoinConferenceRequest)(nil),           // 4: pb.JoinConferenceRequest
	(*JoinConferenceResponse)(nil),          // 5: pb.JoinConferenceResponse
	(*AcceptJoiningRequest)(nil),            // 6: pb.AcceptJoiningRequest
	(*AcceptJoiningResponse)(nil),           // 7: pb.AcceptJoiningResponse
	(*DeclineJoiningRequest)(nil),           // 8: pb.DeclineJoiningRequest
	(*DeclineJoiningResponse)(nil),          // 9: pb.DeclineJoiningResponse
	(*RemoveParticipantRequest)(nil),        // 10: pb.RemoveParticipantRequest
	(*RemoveParticipantResponse)(nil),       // 11: pb.RemoveParticipantResponse
	(*ToggleCameraRequest)(nil),             // 12: pb.ToggleCameraRequest
	(*ToggleCameraResponse)(nil),            // 13: pb.ToggleCameraResponse
	(*ToggleMicRequest)(nil),                // 14: pb.ToggleMicRequest
	(*ToggleMicResponse)(nil),               // 15: pb.ToggleMicResponse
	(*ToggleParticipantCameraRequest)(nil),  // 16: pb.ToggleParticipantCameraRequest
	(*ToggleParticipantCameraResponse)(nil), // 17: pb.ToggleParticipantCameraResponse
	(*ToggleParticipantMicRequest)(nil),     // 18: pb.ToggleParticipantMicRequest
	(*ToggleParticipantMicResponse)(nil),    // 19: pb.ToggleParticipantMicResponse
	(*LeaveConferenceRequest)(nil),          // 20: pb.LeaveConferenceRequest
	(*LeaveConferenceResponse)(nil),         // 21: pb.LeaveConferenceResponse
	(*EndConferenceRequest)(nil),            // 22: pb.EndConferenceRequest
	(*EndConferenceResponse)(nil),           // 23: pb.EndConferenceResponse
}
var file_conference_proto_depIdxs = []int32{
	0,  // 0: pb.Conference.HealthCheck:input_type -> pb.Request
	2,  // 1: pb.Conference.StartConference:input_type -> pb.StartConferenceRequest
	4,  // 2: pb.Conference.JoinConference:input_type -> pb.JoinConferenceRequest
	6,  // 3: pb.Conference.AcceptJoining:input_type -> pb.AcceptJoiningRequest
	8,  // 4: pb.Conference.DeclineJoining:input_type -> pb.DeclineJoiningRequest
	10, // 5: pb.Conference.RemoveParticipant:input_type -> pb.RemoveParticipantRequest
	12, // 6: pb.Conference.ToggleCamera:input_type -> pb.ToggleCameraRequest
	14, // 7: pb.Conference.ToggleMic:input_type -> pb.ToggleMicRequest
	16, // 8: pb.Conference.ToggleParticipantCamera:input_type -> pb.ToggleParticipantCameraRequest
	18, // 9: pb.Conference.ToggleParticipantMic:input_type -> pb.ToggleParticipantMicRequest
	22, // 10: pb.Conference.EndConference:input_type -> pb.EndConferenceRequest
	1,  // 11: pb.Conference.HealthCheck:output_type -> pb.Response
	3,  // 12: pb.Conference.StartConference:output_type -> pb.StartConferenceResponse
	5,  // 13: pb.Conference.JoinConference:output_type -> pb.JoinConferenceResponse
	7,  // 14: pb.Conference.AcceptJoining:output_type -> pb.AcceptJoiningResponse
	9,  // 15: pb.Conference.DeclineJoining:output_type -> pb.DeclineJoiningResponse
	11, // 16: pb.Conference.RemoveParticipant:output_type -> pb.RemoveParticipantResponse
	13, // 17: pb.Conference.ToggleCamera:output_type -> pb.ToggleCameraResponse
	15, // 18: pb.Conference.ToggleMic:output_type -> pb.ToggleMicResponse
	17, // 19: pb.Conference.ToggleParticipantCamera:output_type -> pb.ToggleParticipantCameraResponse
	19, // 20: pb.Conference.ToggleParticipantMic:output_type -> pb.ToggleParticipantMicResponse
	23, // 21: pb.Conference.EndConference:output_type -> pb.EndConferenceResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_conference_proto_init() }
func file_conference_proto_init() {
	if File_conference_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_conference_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartConferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartConferenceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinConferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinConferenceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptJoiningRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptJoiningResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeclineJoiningRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeclineJoiningResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveParticipantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveParticipantResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToggleCameraRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToggleCameraResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToggleMicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToggleMicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToggleParticipantCameraRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToggleParticipantCameraResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToggleParticipantMicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToggleParticipantMicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveConferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaveConferenceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndConferenceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_conference_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndConferenceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_conference_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_conference_proto_goTypes,
		DependencyIndexes: file_conference_proto_depIdxs,
		MessageInfos:      file_conference_proto_msgTypes,
	}.Build()
	File_conference_proto = out.File
	file_conference_proto_rawDesc = nil
	file_conference_proto_goTypes = nil
	file_conference_proto_depIdxs = nil
}
